### ISSUE TITLE
can i send a sms to multiple receiver?

### ISSUE THREAD

**Issue by ramcet** [team-telnyx/telnyx-php#48]
how can i send a sms to multiple receiver with one request?

**Comment by d-telnyx** [comment]
@ramcet Our API does not support Many-to-Many nor One-to-Many messaging today. You'll need to iterate over a list of contacts and create each message individually.

Cheers!

**Comment by ramcet** [comment]
@d-telnyx thanks for response but i want to send same message to all receivers. if i iterate for all receivers will i fail because of your request per minute limits?
