### ISSUE TITLE
PHP 8 support / version

### ISSUE THREAD

**Issue by rico** [team-telnyx/telnyx-php#60]
At the moment, if one installs the package through composer, the `0.0.1` version is installed.

I have forced the installation of the latest version using the `--ignore-platform-reqs` composer option and everything works fine so far.

Please adjust the PHP version requirements or prevent the `0.0.1` version from being installed with PHP 8.

**Comment by d-telnyx** [comment]
@rico _should_ be updated for PHP 8 in v2.5.2: https://packagist.org/packages/telnyx/telnyx-php let us know if it's still not working.

Thank!
